version: '3.8'

services:
  guard:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./guard.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    networks:
      - frontend
      - backend

  web:
    environment:
      - GUARD_ENABLED=true
      - SECURITY_HEADERS=true
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true

volumes:
  guard-logs:
    driver: local
