version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  app:
    image: python:3.9-slim
    command: python -m http.server 8000
    ports:
      - "8001:8000"
    volumes:
      - ../app:/app
    working_dir: /app
