version: '3.8'

services:
  app:
    environment:
      - NODE_ENV=production
    ports: []
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
