version: '3.8'

services:
  oidc-provider:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak123
    ports:
      - "8083:8080"
    depends_on:
      - postgres
    command: start-dev

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak123
    volumes:
      - oidc_data:/var/lib/postgresql/data

  web:
    environment:
      - OIDC_ENABLED=true
      - OIDC_CLIENT_ID=web-app
      - OIDC_CLIENT_SECRET=web-secret
      - OIDC_PROVIDER_URL=http://oidc-provider:8080

volumes:
  oidc_data:
