version: '3.8'

services:
  # Keycloak identity and access management
  keycloak:
    image: quay.io/keycloak/keycloak:20.0
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD:-admin123}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD:-keycloak123}
      - KC_HOSTNAME=localhost
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak/themes:/opt/keycloak/themes:ro
      - ./keycloak/imports:/opt/keycloak/data/import:ro
    depends_on:
      - keycloak-db
    networks:
      - auth
      - frontend
    restart: unless-stopped

  # Keycloak database
  keycloak-db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD:-keycloak123}
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - auth
    restart: unless-stopped

  # OAuth2 Proxy for application protection
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    command:
      - --config=/etc/oauth2-proxy.cfg
    ports:
      - "4180:4180"
    volumes:
      - ./oauth2-proxy.cfg:/etc/oauth2-proxy.cfg:ro
    environment:
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_COOKIE_SECRET}
    depends_on:
      - keycloak
    networks:
      - auth
      - frontend
      - backend
    restart: unless-stopped

  # LDAP server for enterprise integration
  openldap:
    image: osixia/openldap:1.5.0
    environment:
      - LDAP_ORGANISATION=Example Corp
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD:-admin123}
      - LDAP_CONFIG_PASSWORD=${LDAP_CONFIG_PASSWORD:-config123}
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=readonly
      - LDAP_READONLY_USER_PASSWORD=${LDAP_READONLY_PASSWORD:-readonly123}
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ./ldap/bootstrap:/container/service/slapd/assets/config/bootstrap/ldif/custom:ro
    networks:
      - auth
    restart: unless-stopped

  # LDAP admin interface
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - "8181:80"
    depends_on:
      - openldap
    networks:
      - auth
      - frontend
    restart: unless-stopped

  # FreeRADIUS for network authentication
  freeradius:
    image: freeradius/freeradius-server:3.2.0
    ports:
      - "1812:1812/udp" # Authentication
      - "1813:1813/udp" # Accounting
    volumes:
      - ./freeradius/clients.conf:/etc/freeradius/3.0/clients.conf:ro
      - ./freeradius/users:/etc/freeradius/3.0/mods-config/files/authorize:ro
      - freeradius_logs:/var/log/freeradius
    networks:
      - auth
    restart: unless-stopped

  # Vault for secrets management
  vault:
    image: vault:1.12.0
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_ROOT_TOKEN:-root}
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
    ports:
      - "8200:8200"
    volumes:
      - vault_data:/vault/data
      - ./vault/config:/vault/config:ro
    networks:
      - auth
      - backend
    restart: unless-stopped

  # Consul for service discovery and configuration
  consul:
    image: consul:1.14.0
    command: agent -server -bootstrap -ui -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - consul_data:/consul/data
      - ./consul/config:/consul/config:ro
    networks:
      - auth
      - backend
    restart: unless-stopped

volumes:
  keycloak_db_data:
    driver: local
  ldap_data:
    driver: local
  ldap_config:
    driver: local
  freeradius_logs:
    driver: local
  vault_data:
    driver: local
  consul_data:
    driver: local

networks:
  auth:
    driver: bridge
