version: '3.8'

services:
  web:
    environment:
      - NODE_ENV=development
      - DEBUG=true
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: nginx -g 'daemon off;'

  app:
    image: python:3.9
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    volumes:
      - ../app:/app
    command: flask run --host=0.0.0.0

  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:3.9
    volumes:
      - ../:/workspaces:cached
    working_dir: /workspaces
    command: sleep infinity
