[paths]
components_dir = "./components"
base_dir = "base"
environments_dir = "environments"
extensions_dirs = ["extensions"]
build_dir = "./build"

[build]
[build.environments]
available = ["development", "staging", "production"]

[build.environments.development]
extensions = ["monitoring", "logging", "auth", "backup"]

[build.environments.staging]
extensions = ["monitoring", "logging", "auth", "backup"]

[build.environments.production]
extensions = ["monitoring", "logging", "auth", "backup"]
