[paths]
components_dir = "./components"
base_dir = "base"
environments_dir = "environments"
extensions_dirs = ["extensions"]
build_dir = "./build"

[build]
environments = ["development", "staging", "production"]
extensions = ["monitoring", "logging", "auth", "backup"]
