version: '3.8'

services:
  # Development-specific overrides
  web:
    ports:
      - "8080:80" # Different port for development
    volumes:
      - ./nginx-dev.conf:/etc/nginx/nginx.conf:ro
    environment:
      - DEBUG=true

  app:
    environment:
      - NODE_ENV=development
      - DEBUG=*
      - HOT_RELOAD=true
    volumes:
      - ./app:/app
      - ./app/src:/app/src:cached # Hot reload support
      - node_modules:/app/node_modules
    command: npm run dev
    ports:
      - "3000:3000" # Expose for direct access in dev

  database:
    environment:
      - POSTGRES_DB=appdb_dev
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
    ports:
      - "5432:5432" # Expose for development tools

  cache:
    ports:
      - "6379:6379" # Expose for development tools

  # Development-only services
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - backend

volumes:
  # Use named volumes for faster file access in development
  node_modules:
    driver: local
