[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-ar"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
ar = "aarch64-linux-gnu-ar"

# macOS targets using Zig cc as cross-linker
[target.x86_64-apple-darwin]
linker = "./.cargo/zig-cc.sh"
rustflags = ["-C", "link-arg=-target", "-C", "link-arg=x86_64-macos-none"]

[target.aarch64-apple-darwin]
linker = "./.cargo/zig-cc.sh"
rustflags = ["-C", "link-arg=-target", "-C", "link-arg=aarch64-macos-none"]
