[paths]
components_dir = "./custom-components"
base_dir = "core"
environments_dir = "envs"
extensions_dirs = ["addons", "plugins", "modules"]
build_dir = "./output"

[build]
[build.environments]
available = ["dev", "qa"]

[build.environments.dev]
extensions = ["cache", "security"]

[build.environments.qa]
extensions = ["cache", "security"]
