version: '3.8'

services:
  # QA environment overrides
  api:
    environment:
      - NODE_ENV=testing
      - API_URL=https://qa-api.example.com
      - ENABLE_TESTING=true
      - LOG_LEVEL=debug
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  db:
    environment:
      - MYSQL_ROOT_PASSWORD=qaroot
      - MYSQL_DATABASE=appdb_qa
      - MYSQL_USER=qauser
      - MYSQL_PASSWORD=qapass
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  # QA-specific services
  selenium-hub:
    image: selenium/hub:4.11.0
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=4
      - GRID_BROWSER_TIMEOUT=30
      - GRID_TIMEOUT=30
    networks:
      - app-network

  selenium-chrome:
    image: selenium/node-chrome:4.11.0
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=2
      - NODE_MAX_SESSION=2
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - app-network

  test-runner:
    image: node:18-alpine
    working_dir: /tests
    volumes:
      - ./tests:/tests
      - test_reports:/tests/reports
    environment:
      - SELENIUM_HUB=http://selenium-hub:4444
      - API_BASE_URL=http://api:3000
    command: |
      sh -c "
        npm install
        npm run test:e2e
      "
    depends_on:
      - api
      - selenium-hub
    networks:
      - app-network

volumes:
  test_reports:
    driver: local
