version: '3.8'

services:
  api:
    image: node:18-alpine
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
