version: '3.8'
services:
  oidc:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    ports:
      - "4180:4180"
    environment:
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_CLIENT_ID=${OIDC_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OAUTH2_PROXY_OIDC_ISSUER_URL=${OIDC_ISSUER_URL}
      - OAUTH2_PROXY_COOKIE_SECRET=${OIDC_COOKIE_SECRET}
      - OAUTH2_PROXY_UPSTREAM=http://app:80
    depends_on:
      - app
