[paths]
components_dir = "./components"
base_dir = "base"
environments_dir = "environments"
extensions_dirs = ["extensions"]
build_dir = "./build"

[build]
# Define named combos as inline tables
combos = { security = [
    "oidc",
    "guard",
], monitoring = [
    "prometheus",
    "grafana",
    "alertmanager",
], development = [
    "debugging",
    "profiling",
] }

# New environments API
[build.environments]
available = ["dev", "staging", "prod"]

# Per-environment configurations
[build.environments.dev]
extensions = ["logging"]
combos = ["security", "development"]

[build.environments.staging]
extensions = ["backup"]
combos = ["monitoring"]

[build.environments.prod]
combos = ["security", "monitoring"]
