[paths]
components_dir = "./components"
base_dir = "base"
environments_dir = "environments"
extensions_dirs = ["extensions"]
build_dir = "./build"

[build]
# Global environments list
environments = ["dev", "staging", "prod"]

# Define named combos as inline tables
combos = { security = [
    "oidc",
    "guard",
], monitoring = [
    "prometheus",
    "grafana",
    "alertmanager",
], development = [
    "debugging",
    "profiling",
] }

# Per-environment filtering via targets
[build.targets.dev]
extensions = ["logging"]
combos = ["security", "development"]

[build.targets.staging]
extensions = ["backup"]
combos = ["monitoring"]

[build.targets.prod]
combos = ["security", "monitoring"]
