[paths]
components_dir = "./components"
base_dir = "base"
environments_dir = "environments"
extensions_dirs = ["extensions"]
build_dir = "./build"

[build]
[build.environments]
available = ["devcontainer", "internal"]

[build.environments.devcontainer]
extensions = ["oidc", "guard"]

[build.environments.internal]
extensions = ["oidc", "guard"]
